export enum ACTION_TYPES {
    FETCH_DATA = 'FETCH_DATA',
    FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
    FETCH_DATA_ERROR = 'FETCH_DATA_ERROR',
    FETCH_OS_SPEC = 'FETCH_OS_SPEC',
    FETCH_OS_SPEC_SUCCESS = 'FETCH_OS_SPEC_SUCCESS',
    FETCH_OS_SPEC_ERROR = 'FETCH_OS_SPEC_ERROR',
}